export const scales = [
  'aeolian',
  'altered',
  'augmented',
  'augmented heptatonic',
  'balinese',
  'bebop',
  'bebop locrian',
  'bebop major',
  'bebop minor',
  'chromatic',
  'composite blues',
  'diminished',
  'dorian',
  'dorian #4',
  'dorian b2',
  'double harmonic lydian',
  'double harmonic major',
  'egyptian',
  'enigmatic',
  'flamenco',
  'flat six pentatonic',
  'flat three pentatonic',
  'half-whole diminished',
  'harmonic major',
  'harmonic minor',
  'hirajoshi',
  'hungarian major',
  'hungarian minor',
  'ichikosucho',
  'in-sen',
  'ionian pentatonic',
  'iwato',
  'kafi raga',
  'kumoijoshi',
  'leading whole tone',
  'locrian',
  'locrian #2',
  'locrian 6',
  'locrian major',
  'locrian pentatonic',
  'lydian',
  'lydian #5P pentatonic',
  'lydian #9',
  'lydian augmented',
  'lydian diminished',
  'lydian dominant',
  'lydian dominant pentatonic',
  'lydian minor',
  'lydian pentatonic',
  'major',
  'major augmented',
  'major blues',
  'major pentatonic',
  'malkos raga',
  'melodic minor',
  "messiaen's mode #3",
  "messiaen's mode #4",
  "messiaen's mode #5",
  "messiaen's mode #6",
  "messiaen's mode #7",
  'minor #7M pentatonic',
  'minor bebop',
  'minor blues',
  'minor hexatonic',
  'minor pentatonic',
  'minor six diminished',
  'minor six pentatonic',
  'mixolydian',
  'mixolydian b6',
  'mixolydian pentatonic',
  'mystery #1',
  'neopolitan major',
  'neopolitan major pentatonic',
  'oriental',
  'pelog',
  'persian',
  'phrygian',
  'phrygian dominant',
  'piongio',
  'prometheus',
  'prometheus neopolitan',
  'purvi raga',
  'ritusen',
  'romanian minor',
  'scriabin',
  'six tone symmetric',
  'spanish heptatonic',
  'super locrian pentatonic',
  'todi raga',
  'ultralocrian',
  'vietnamese 1',
  'whole tone',
  'whole tone pentatonic'
] as const

export const scalesMap: Map<number, typeof scales[number]> = scales.reduce(
  (acc, scaleName, i) => {
    acc.set(i, scaleName)
    return acc
  },
  new Map()
)
